apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sd3gg1zo5-go
  janus-idp.io/tekton: sd3gg1zo5-go
  backstage.io/kubernetes-id: sd3gg1zo5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sd3gg1zo5-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
